# Generated by Django 6.0.6 on 2026-06-17 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField()),
                ('exception_type', models.PositiveIntegerField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_dates', to='core.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(db_index=True, max_length=255)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='core.feed')),
            ],
            options={
                'verbose_name_plural': 'calendars',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(blank=True, default='', max_length=255)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_url', models.URLField(max_length=500)),
                ('agency_timezone', models.CharField(max_length=255)),
                ('agency_lang', models.CharField(blank=True, default='pt', max_length=2)),
                ('agency_phone', models.CharField(blank=True, max_length=127, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='core.feed')),
            ],
            options={
                'verbose_name_plural': 'agencies',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_index=True, max_length=255)),
                ('route_short_name', models.CharField(blank=True, db_index=True, max_length=63, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('route_type', models.PositiveIntegerField(choices=[(0, 'Tranvia'), (1, 'Metro'), (2, 'Ferrocarril'), (3, 'Ônibus'), (4, 'Ferry'), (5, 'Teleférico'), (6, 'Gôndola'), (7, 'Funicular'), (11, 'Trolebus'), (12, 'Monotrilho')], default=3)),
                ('route_color', models.CharField(blank=True, max_length=6, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=6, null=True)),
                ('route_sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.agency')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.feed')),
            ],
            options={
                'ordering': ['route_sort_order', 'route_short_name'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(db_index=True, max_length=255)),
                ('stop_code', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_name', models.CharField(db_index=True, max_length=255)),
                ('stop_desc', models.TextField(blank=True, null=True)),
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('stop_lon', models.FloatField(blank=True, null=True)),
                ('location_type', models.PositiveIntegerField(blank=True, null=True)),
                ('parent_station', models.CharField(blank=True, default='', max_length=255)),
                ('wheelchair_boarding', models.PositiveIntegerField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_ref', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('trip_id', models.CharField(db_index=True, max_length=255)),
                ('trip_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('trip_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('direction_id', models.PositiveIntegerField(blank=True, null=True)),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shape_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('wheelchair_accessible', models.PositiveIntegerField(default=0)),
                ('bikes_allowed', models.PositiveIntegerField(default=0)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.feed')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.route')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(db_index=True, max_length=255)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.PositiveIntegerField()),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='core.feed')),
            ],
            options={
                'ordering': ['shape_id', 'shape_pt_sequence'],
                'indexes': [models.Index(fields=['shape_id', 'shape_pt_sequence'], name='core_shape_shape_i_ec965a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=8, null=True)),
                ('stop_sequence', models.PositiveIntegerField()),
                ('pickup_type', models.PositiveIntegerField(default=0)),
                ('drop_off_type', models.PositiveIntegerField(default=0)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
                ('timepoint', models.BooleanField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='core.feed')),
                ('stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='core.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='core.trip')),
            ],
            options={
                'ordering': ['stop_sequence'],
                'indexes': [models.Index(fields=['trip', 'stop_sequence'], name='core_stopti_trip_id_652a59_idx')],
            },
        ),
    ]
